# This file was generated by GoReleaser. DO NOT EDIT.
cask "fifawc26" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "236431fedf7f879434ecaee31a61165480b61bc3b2ab23fa16cd3850ae7a7452"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c4c0acb427b280a32b0daa8d8fb97ab0d7196587a5a721fd0881bcd12010161"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5bec0012e57ada5185b826b862da6d66eab0c6d587bce5e57ba96225352e61ce"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "30f0c9d9f27b248b24d831e559bc0b4f0f5a051be37e05336fbf57d9590411ad"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "fifawc26"
  desc "FIFA World Cup 2026 in your terminal"
  homepage "https://github.com/charliehustlr1792/fifawc26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fifawc26"

  # No zap stanza required

end
