# This file was generated by GoReleaser. DO NOT EDIT.
cask "fifawc26" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "fcf3552eab4c9a20e7931daef6c2b11053c85f4b618d2b6242720e4d1c305b4e"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8035f59de23bba27f82e911c25498a5cb0de723dd61e3da5f908aab45dc44266"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de21c1ba2dd8d02039ad01f733e94243b370fa457287c99018ea99443a4c6f16"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "023c935c3e70c74d414a422f2ea2fa84f644b201de5f38efda2f03934c725332"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "fifawc26"
  desc "FIFA World Cup 2026 in your terminal"
  homepage "https://github.com/charliehustlr1792/fifawc26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fifawc26"

  # No zap stanza required

end
