# This file was generated by GoReleaser. DO NOT EDIT.
cask "fifawc26" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "eae89a7e275b24da1b9aa6198fe29ec6e6027c5ae38bf34b6e8b673945c2c467"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7472d2cb5254ee8a17d8155e4adb40bab3b86bb02bacd229fc4b69b73b2a7b71"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c81fbe6ec081b7536e9158fa6609bd81d44cfc11cfb96d8e620f9ad594ad0a3d"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2881ddff003b1ed080a87878d30c272999e9d679fcb4d2675c9acd82152c38bc"
      url "https://github.com/charliehustlr1792/fifawc26/releases/download/v#{version}/fifawc26_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "fifawc26"
  desc "FIFA World Cup 2026 in your terminal"
  homepage "https://github.com/charliehustlr1792/fifawc26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fifawc26"

  # No zap stanza required

end
